[package]
name = "minter"
version = { workspace = true }
edition = { workspace = true }

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
ic-cdk-timers = { workspace = true }
icrc-ledger-types = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
pocket-ic = { workspace = true }

[lints]
workspace = true
