[workspace]
members = [
    "src/minter"
]
resolver = "2"

[workspace.package]
version = "0.0.2"
edition = "2021"

[workspace.dependencies]
ic-cdk = "0.20"
ic-cdk-timers = "1"
candid = "0.10"
icrc-ledger-types = "0.1"
serde = { version = "1", features = ["derive"] }
pocket-ic = "15.0"

[workspace.lints.rust]
warnings = "deny"
unused_attributes = "deny"
redundant_imports = "deny"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
enum_glob_use = "deny"
single_component_path_imports = "warn"
absolute_paths = "deny"
allow_attributes = "deny"
std_instead_of_core = "deny"
unseparated_literal_suffix = "deny"
redundant_test_prefix = "deny"
str_to_string = "deny"
string_add = "deny"
suspicious_xor_used_as_pow = "deny"
missing_errors_doc = { level = "allow", priority = 1 }
missing_panics_doc = { level = "allow", priority = 1 }
unnecessary_wraps = { level = "allow", priority = 1 }
too_many_lines = { level = "allow", priority = 1 }
format_push_string = { level = "allow", priority = 1 }
similar_names = { level = "allow", priority = 1 }
