disallowed-macros = [
    { path = "std::print", reason = "Use ic_cdk::print instead" },
    { path = "std::println", reason = "Use ic_cdk::println instead" },
    { path = "std::eprint", reason = "Use ic_cdk::eprint instead" },
    { path = "std::eprintln", reason = "Use ic_cdk::eprintln instead" },
]

absolute-paths-max-segments = 1
absolute-paths-allowed-crates = []
