name: Checks

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  merge_group:
  workflow_dispatch:

permissions: {}

jobs:
  format:
    name: Format
    runs-on: ubuntu-24.04
    concurrency:
      group: checks-format-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: write # Required to push formatting/lint fixes back to the repo (add-and-commit).

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Format
        run: npm run format

      - name: Check for Changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Fail for formatting issues without personal access token
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          echo "Formatting changes are needed but couldn't be committed because the personal access token isn't available or this isn't a pull request."
          exit 1

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    concurrency:
      group: checks-lint-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Lint
        run: npm run lint

  checks-pass:
    name: Checks Pass
    if: always()
    needs: ['format', 'lint']
    runs-on: ubuntu-24.04
    concurrency:
      group: checks-pass-${{ github.ref }}
      cancel-in-progress: false
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/needs_success
        with:
          needs: '${{ toJson(needs) }}'
